### ISSUE TITLE
twitter credentials not sent to sockethub when changed

### ISSUE THREAD

**Issue by michielbdejong** [unhosted/microblogging#3]
i connected to sockethub first (with no twitter credentials) and then updated them later. but then when i click 'sync', it still tries to use the old ones, it doesn't seem to do 'set' again.

i was able to fix it by restarting sockethub and hitting 'connect' again in the sockethub widget, but that shouldn't be necessary

**Comment by ggrin** [comment]
that is a proble, 
will install eventhandlers for credentials-module so they react on change events 
maybe also on the inputs
